modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="sbsshot"
version="1.0.0"
displayName="SBSShot"
logoFile="pack.png"
description="VR/HMD向けのステレオ立体画像形式（.pns）でスクリーンショットします。"

[[dependencies.sbsshot]]
    modId="neoforge"
    type="required"
    versionRange="[26.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbsshot]]
    modId="minecraft"
    type="required"
    versionRange="[26.1,)"
    ordering="NONE"
    side="BOTH"
