modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="sbsshot"
version="${version}"
displayName="SBSShot"
logoFile="pack.png"
description="VR/HMD向けのステレオ立体画像をスクリーンショットします。"

[[dependencies.sbsshot]]
    modId="neoforge"
    type="required"
    versionRange="[${mc_ver},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sbsshot]]
    modId="minecraft"
    type="required"
    versionRange="[${mc_ver},)"
    ordering="NONE"
    side="BOTH"
